import AsyncStorage from '@react-native-async-storage/async-storage';
import { StorageService } from './StorageService';
import { createApiService } from './api';

export interface SyncItem {
    id: string; // The ID of the sync item in the queue
    url: string;
    method: 'POST' | 'PUT' | 'DELETE';
    body?: any;
    timestamp: number;
    tempId?: string; // The local temp ID generated by StorageService (e.g., 'temp_1234')
}

class OfflineSyncManager {
    private queue: SyncItem[] = [];
    private isSyncing = false;

    async loadQueue() {
        try {
            const storedQueue = await AsyncStorage.getItem('offline_queue');
            if (storedQueue) {
                this.queue = JSON.parse(storedQueue);
            }
        } catch (e) {
            console.error('Failed to load offline queue details', e);
        }
    }

    private async saveQueue(newQueue: SyncItem[]) {
        try {
            await AsyncStorage.setItem('offline_queue', JSON.stringify(newQueue));
            this.queue = newQueue;
        } catch (e) {
            console.error('Failed to save offline queue', e);
        }
    }

    async queueRequest(url: string, method: 'POST' | 'PUT' | 'DELETE', body?: any, tempId?: string) {
        // Ensure queue is loaded first
        if (this.queue.length === 0) {
            await this.loadQueue();
        }

        const newItem: SyncItem = {
            id: Date.now().toString(),
            url,
            method,
            body,
            timestamp: Date.now(),
            tempId,
        };
        
        const newQueue = [...this.queue, newItem];
        await this.saveQueue(newQueue);
        console.log('[OfflineSync] Request queued:', newItem.method, newItem.url);
    }

    async syncPendingRequests(getToken: () => Promise<string | null>) {
        if (this.isSyncing) return;
        
        await this.loadQueue();
        if (this.queue.length === 0) return;

        this.isSyncing = true;
        console.log(`[OfflineSync] Syncing ${this.queue.length} pending requests...`);
        
        const token = await getToken();
        if (!token) {
             this.isSyncing = false;
             return;
        }

        const headers = {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`,
        };

        const remainingQueue: SyncItem[] = [];

        for (const item of this.queue) {
            try {
                // If this is a PUT/DELETE for an item we JUST created offline, its URL might still have 'temp_1234'.
                // If Server Reconciliation already swapped the local DB, we need to make sure we swap it in the URL too?
                // For simplicity, we assume UI edits push the *current* ID to the URL. If the UI still sees 'temp_1234',
                // we should hold this request until the POST succeeds and swaps the ID.
                
                // Safety check: Don't PUT/DELETE a temp ID if we haven't synced its POST yet.
                // The queue processes in order, so the POST should go first.
                
                const res = await fetch(item.url, {
                    method: item.method,
                    headers,
                    body: item.body ? JSON.stringify(item.body) : undefined,
                });

                if (!res.ok) {
                    if (res.status >= 500) {
                        remainingQueue.push(item); // Retry 5xx errors later
                    } else if (res.status === 404) {
                        // Not found - server already deleted it or it never existed. Drop it to prevent blocking queue.
                        console.warn(`[OfflineSync] Dropping 404 on ${item.method} ${item.url}`);
                    } else {
                        console.error(`[OfflineSync] Failed to sync item ${item.id} (${item.method} ${item.url}): ${res.status}`);
                        remainingQueue.push(item); // Requeue by default to be safe, except 404
                    }
                } else {
                    const responseData = await res.json().catch(() => null);
                    console.log(`[OfflineSync] Synced item ${item.id} (${item.method})`);
                    
                    // Server Reconciliation: POST created a real ID mapping for our tempId
                    if (item.method === 'POST' && item.tempId && responseData && responseData.id) {
                        const realId = responseData.id;
                        console.log(`[OfflineSync] Reconciling tempId: ${item.tempId} -> realId: ${realId}`);
                        
                        // 1. Update StorageService directly
                        await StorageService.replaceTempId(item.tempId, realId);
                        
                        // 2. Cascade update to any waiting items in the queue
                        // e.g., if we POSTed a temp todo, and then PUT mutated it immediately, 
                        // the PUT in the queue currently has a temp url `/todos/temp_1234`. We must fix it.
                        // We must fix it in `remainingQueue` AND `this.queue` (future loops)
                        for (let futureItem of this.queue) {
                            if (futureItem.url.includes(item.tempId)) {
                                futureItem.url = futureItem.url.replace(item.tempId, String(realId));
                                console.log(`[OfflineSync] Cascade updated queued URL to ${futureItem.url}`);
                            }
                            // Also check bodies if JSON contains references (rare, but good practice)
                        }
                    }
                }
            } catch (error) {
                console.error(`[OfflineSync] Network error syncing item ${item.id}`, error);
                remainingQueue.push(item); // Keep if network error
                break; // Stop syncing if network drops completely to guarantee causal ordering
            }
        }

        await this.saveQueue(remainingQueue);
        this.isSyncing = false;
    }

    async sync7DaysHistory(getToken: () => Promise<string | null>) {
        try {
            console.log('[OfflineSync] Fetching 7-day deep cache history...');
            // Need the API instance just for fetching
            const api = createApiService(getToken);
            
            // Generate a 'date' param corresponding to 7 days ago
            const d = new Date();
            d.setDate(d.getDate() - 7);
            const sevenDaysAgo = d.toISOString().split('T')[0];

            // In our current backend, getTodos without date fetches ALL, getCalendar fetches ALL. 
            // We'll rely on our existing endpoints first, since our DB is small for a single user.
            // But if we need true 7-day limits, we'll hit the endpoints as they are and store them.
            
            // Get all tasks, medicines (global), calendar (global stats), and the last 7 daily logs/metrics
            const [allTodos, calendarData, medicines] = await Promise.all([
                api.getTodos(),             // Backend returns all standard user tasks
                api.getCalendarData(),      // Backend returns all summary stats
                api.getMedicines()          // Backend returns all medicines
            ]);

            await StorageService.syncTodos(allTodos);
            await StorageService.syncCalendar(calendarData);
            await StorageService.syncMedicines(medicines);

            // Fetch the last 7 days of detailed daily logs & health metrics individually
            const tempDate = new Date();
            for (let i = 0; i < 7; i++) {
                const dateKey = tempDate.toISOString().split('T')[0];
                
                const [log, metrics, food] = await Promise.all([
                    api.getDailyLog(dateKey).catch(() => null),
                    api.getHealthMetrics(dateKey).catch(() => null),
                    api.getDailyFoodLog(dateKey).catch(() => null)
                ]);

                if (log) await StorageService.updateDailyLog(log);
                if (metrics) await StorageService.updateHealthMetrics(metrics);
                // Food omitted from aggressive cache for now unless specifically needed for history

                tempDate.setDate(tempDate.getDate() - 1); // Go back one day
            }
            
            const now = new Date().toISOString();
            await AsyncStorage.setItem('last_synced', now);
            console.log('[OfflineSync] Deep cache sync complete.');
            
        } catch (e) {
            console.error('[OfflineSync] Failed to pull 7-day history', e);
        }
    }
}

export const OfflineSyncService = new OfflineSyncManager();
